## name: CyberXero
## author: MurderFromMars
## license: GNU GPL
## upstream: https://github.com/MurderFromMars/Cosmic-Cyberpunk-Kitten-Theme

background            #000000
foreground            #44a8ab
selection_background  #44a8ab
selection_foreground  #000000
cursor                #d00d11

# Black, Gray, Silver, White

color0                #000000
color8                #44a8ab
color7                #44a8ab
color15               #44a8ab

# Red

color1                #d00d11
color9                #d00d11

# Green

color2                #44a8ab
color10               #44a8ab

# Yellow

color3                #d00d11
color11               #d00d11

# Blue

color4                #44a8ab
color12               #44a8ab

# Purple

color5                #d00d11
color13               #d00d11

# Teal

color6                #44a8ab
color14               #44a8ab
